### ISSUE TITLE
cdk error - ecsTaskExecutionRole already exists 

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/dataops-platform-airflow-dbt#1]
I was getting this error when I ran `make deploy`. 
AirflowClusterStack: creating CloudFormation changeset...
2:20:17 PM | CREATE_FAILED        | AWS::IAM::Role      | ecsTaskExecutionRole34F54B99
ecsTaskExecutionRole already exists

Looks like the issue is because the IAM role (ecsTaskExecutionRole) already exists. 

You can resolve this issue if you add custom name to the IAM role on line 23 of /infra/stacks/airflow_cluster_stack.py

**Comment by rickybasse** [comment]
Hi @dalbhanj! Thanks for raising this. Fixed in https://github.com/aws-samples/dataops-platform-airflow-dbt/pull/5
