### ISSUE TITLE
ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret

### ISSUE THREAD

**Issue by Tres33** [aws-samples/dataops-platform-airflow-dbt#12]
When I run make deploy, I get a ResourceInitializationError error while initializing the fargate services in MyCluster. I was able to fix this by setting `assign_public_ip` to `True` for the 3 services in `dataops-infra/infra/stacks/fargate_services/airflow.py`. However, when I run the `redshift_transformations` dag on Airflow, I get the same error when running task `dbt-cdk`. May I know how I could debug this? Thanks!

**Comment by dzeno** [comment]
Hello @Tres33 ! Thanks for raising this issue. Fixed in https://github.com/aws-samples/dataops-platform-airflow-dbt/pull/13

**Comment by Tres33** [comment]
Works on my end. Thanks!
